### ISSUE TITLE
Why did you leave Xamarin?

### ISSUE THREAD

**Issue by paulyoung** [7sharp9/AMA#3]

**Comment by 7sharp9** [comment]
When Microsoft bought Xamarin there was a date at which Xamarin was legally owned by Microsoft, at that point I had to decide if I wanted to be a Microsoft Employee or not.  

There was a discussion around the scope of my position, the direction of F#, and also about money.  In the end the discussion failed, neither the scope, direction or money was negotiable so I walked away dissatisfied and disappointed.

**Comment by realvictorprm** [comment]
If money wasn't negotiable they must have thought of paying you less than before. Very sad. To read this at all is sad enough.
