### ISSUE TITLE
Why didn't we finish Fracture?

### ISSUE THREAD

**Issue by panesofglass** [7sharp9/AMA#4]

**Comment by 7sharp9** [comment]
I think we both got a bit burned out and lost direction.  I know I did.

Theres also the fact I moved from developing the code on a Windows VM to a Mac with Mono and encountered the really poor network performance of Mono.  I think with libuv as it stands it would be viable nowadays.  

There are also Windows only RIO bindings that are super high performance but thats a whole other story.

**Comment by 7sharp9** [comment]
There was a list of interesting things penned for Fracture-IO aka Ithaqua, I have them somewhere ...
