### ISSUE TITLE
What's the status of your Elixir/F# prototyping?

### ISSUE THREAD

**Issue by panesofglass** [7sharp9/AMA#5]

**Comment by 7sharp9** [comment]
If you mean the [Metamatic blog post](http://7sharpnine.com/2015/07/12/2015-07-08-meta-matic/) then thats all it is a prototype, its a rather large project to bring something like that to life, I just wanted to plant the seed and a direction for someone else to take the lead on, while I got to have all the fun doing some initial trailblazing :-)
