### ISSUE TITLE
Which mobile app framework do you currently favour?

### ISSUE THREAD

**Issue by JonCanning** [7sharp9/AMA#6]

**Comment by 7sharp9** [comment]
I prefer Xamarin Native as you get native access to both Android and iOS and get to use F#.  

You know up front you will have to write more code than say Xamarin Forms, but you know exactly how its going to behave and work, the price paid for platform abstractions is often really high when you hit outliers or custom components.  React native with Fable is also a consideration, I find the abstraction offered there often work better than Xamarin Forms.

I also have no qualms about using Swift and Kotlin to do native development, the downside is you don't get to share any common code unless you generate integration code with a code generator for both platforms, Heck you could probably knock one up with a F# -> Swift/Kotlin transpilar :-p
