### ISSUE TITLE
What's the future of F#?

### ISSUE THREAD

**Issue by vasily-kirichenko** [7sharp9/AMA#7]

**Comment by 7sharp9** [comment]
Ohhh thats a good one, difficult to answer.

I think F# will continue to be super niche and not get an major new features like fully working Type Providers that are not hobbled in some way.

I think the tooling will gradually get less and less contributions and become less maintained and more buggy as the open source contributors burn out.  

The mobile part of F# could possibly die out in the future as the users get dissatisfied with the poor tooling, maybe there will be a move to Fable with React Native, although that also has only a small amount of users, with an even smaller support base.

I think there will still remain a Windows centric base for F# but that could gradually decline over time too.  

Of course I would like F# to survive but there just isn't the user base or support base, be that paid or open source contributors to make that happen.

**Comment by sivabudh** [comment]
I find it ironic that one of the most feature complete programming languages on the planet will "die out." I doubt F# will ever become the next "node.js" but I doubt the ecosystem will ever die out either. Lisp will have to die 10 times over before F# will.

**Comment by Krzysztof-Cieslak** [comment]
Language quality and feature set is probably least important factor in the language success

**Comment by isaksky** [comment]
@Krzysztof-Cieslak good point. Though I think you may be ignoring the impact of language on the ecosystem. Consider how many of the most popular libraries/frameworks in Elixir, Rust, Haskell, etc use macros, compiler plugins, and other features not available in F# (and for which there is no good substitute).

**Comment by 7sharp9** [comment]
@sivabudh The F# ecosystem is .Net, I don't think .Net will die out, I do think there will be more uptake of the alternatives like Scala/Kotlin using the JVM ecosystem.  

In terms of tooling quality, both Windows tooling and x-plat tooling are making a big impact on users first impressions, e.g. a bad one with the regular breakages on Windows and Mono.  The problem stems to the fact the C# drives the business, C# is .Net.

With F# for mobile, although I advocate using it and have built a lot of the tools, and made platforms such as iOS available for F#, I have never seen a dramatic uptake of F# usage.  Its been somewhat of a labour of love for me and its sad to see so little usage in the wild.
