### ISSUE TITLE
What's your go to stack?

### ISSUE THREAD

**Issue by JonCanning** [7sharp9/AMA#8]
Say you were building a simple CRUD API for a business and there were no non-functional requirements, JFDI.

Platform, language, IDE, hosting, DB, framework etc

**Comment by 7sharp9** [comment]
I would be tempted to use the JVM with something like Kotlin, theres come a time where .Net and F# are so unstable to the point where doing anything other than Windows development is only just viable.

Platform: JVM
Language: Kotlin/maybe Clojure
IDE: vscode/sublime
Hosting: azure
DB/frameworks who knows Ive tended to work in niches for the last few years, compilers, tooling, mobile so I would have to do a little research to refresh my memory.

**Comment by 7sharp9** [comment]
_If it was heavily web oriented I would open up my Elm toolbox_
